### ISSUE TITLE
Não funciona no Firefox 67.0.4 (64 -bit) a usar TamperMonkey.

### ISSUE THREAD

**Issue by poydflink** [dippas/DeleteNonio#1]
Site: https://www.publico.pt/2019/06/20/culturaipsilon/noticia/presidente-portugues-usado-promover-serie-espanhola-casa-papel-1877114

**Comment by dippas** [comment]
@poydflink  vou precisar de mais informação. acabei de instalar o Tampermonkey no Firefox v67.0.4(64-bit) e funcionou (inclusive vi a popup a aparecer e uns segundos depois despareceu)
