### ISSUE TITLE
Páginas com duplo "elevador" e página com texto aumentado como se tivesse sido feito zoom.

### ISSUE THREAD

**Issue by Windows10User2** [dippas/DeleteNonio#10]
Na versão mais recente do Google Chrome x64 e após instalar e ativar a extensão DeleteNonio, há páginas que ficam com duplo "elevador" e pelo menos uma com o texto como se tivesse sido feito zoom.

![Captura de Ecrã (22)](https://user-images.githubusercontent.com/57052438/89471204-71e1f280-d775-11ea-9957-60021fdcf23b.png)
![Captura de Ecrã (23)](https://user-images.githubusercontent.com/57052438/89471208-74444c80-d775-11ea-919f-7a0719e2ad20.png)

**Comment by dippas** [comment]
@Windows10User2 não é preciso criar novos issues dado que está tudo corrigido na versão 1.6.1 que infelizmente na Chrome store demora um pouco mais a ser aprovada

**Comment by dippas** [comment]
Duplicate of #6
