### ISSUE TITLE
site expresso

### ISSUE THREAD

**Issue by hsl1** [dippas/DeleteNonio#11]
no site do expresso continua a aparecer a janela do login que pertence ao nonio no fim da página

![image](https://user-images.githubusercontent.com/11902467/90063977-069ea000-dce2-11ea-9faa-1f533dcd127d.png)

![image](https://user-images.githubusercontent.com/11902467/90064157-449bc400-dce2-11ea-8a21-5d86d06b8ae6.png)

**Comment by dippas** [comment]
Duplicate of #4

**Comment by hsl1** [comment]
desculpa mas a #4 está locked.

**Comment by dippas** [comment]
@hsl1  certifique-se que tem a ultima versão da extensão, pode também limpar a cache do browser,  acabei de testar e a popup desaparece bem.

**Comment by hsl1** [comment]
tenho sim a 1.6.1
Foi neste artigo https://expresso.pt/economia/2020-08-12-TVI-Mario-Ferreira-arrisca-se-a-ser-obrigado-a-lancar-OPA-concorrente-a-da-Cofina e aparece essa janela, já limpei tudo

**Comment by dippas** [comment]
@hsl1  fixed in v1.6.2, fizeram alterações recentes no site

**Comment by hsl1** [comment]
já estava antes mas ok desde que fique bem...

**Comment by hsl1** [comment]
> @hsl1 fixed in v1.6.2, fizeram alterações recentes no site
já estava antes mas ok desde que fique bem...

**Comment by dippas** [comment]
@hsl1  eu já tinha corrigido da 1º vez que reportaste, entretanto eles fizeram alterações no código deles, era isso que me estava a referir

E afinal a versão 100% correcta so está na v1.6.3 (como ja tinha feito pedido de revisão na chrome store para a v.1.6.2, só consigo atualizar após esta versão estar aprovada) na extensão do Firefox e nos usersScripts  já está atualizado
