### ISSUE TITLE
scroll bar In Private

### ISSUE THREAD

**Issue by hsl1** [dippas/DeleteNonio#12]
No modo inPrivate por vezes ainda aparece a dupla barra de scroll.
Às vezes chega fazer f5 outras vezes fica lá na mesma

Acho que tem a haver com que ter que aceitar a janela dos cookies cá em baixo, mas testei algumas vezes após aceitar e mesmo assim aparece duas vezes o scroll bar. Fechei várias vezes o In Private a abri de novo.

![image](https://user-images.githubusercontent.com/11902467/90109241-709b6180-dd43-11ea-9cc8-bf7afe94158b.png)

PS: estava a testar aquela situação de ontem mas ainda aparece n v1.6.2... vou esperar pela última

**Comment by dippas** [comment]
@hsl1  ficou resolvido com a v1.6.3

**Comment by hsl1** [comment]
aqui ainda acontece tanto em InPrivate o sroll como no normal o login ainda mostra em baixo.
Basta abrir a janela e não clicar na janela do cookiese ve o duplo scroll

Já estou na nova versão e limpei a cache

**Comment by hsl1** [comment]
![image](https://user-images.githubusercontent.com/11902467/90234067-f3d9b780-de16-11ea-98fa-4e9b90a51874.png)
Quando puder veja de novo o site parece que alteraram e agora está com duplo scroll de novo

**Comment by dippas** [comment]
@hsl1  so acontece no site expresso e nem é sempre, a solução passa por fazer um (ou varios) refresh na pagina. Não há muito que possa fazer.
