### ISSUE TITLE
Ainda tenho duplo scroll algumas vezes até atualizar a página.

### ISSUE THREAD

**Issue by Windows10User2** [dippas/DeleteNonio#13]
Ainda tenho duplo scroll algumas vezes até atualizar a página.

**Comment by dippas** [comment]
@Windows10User2  é só num ou noutro site. não posso corrigir essa situação.

**Comment by dippas** [comment]
Duplicate of #12

**Comment by Windows10User2** [comment]
Eu sei que isto é off-topic, mas sabes como bloquear esta (primeira imagem anexada) publicidade irritanto em cada separador do Record.pt usando o uBlock Origin no Chrome para Windows? Se eu ativá-lo, ele bloqueia a publicidade mas "estraga" os separadores como podes ver na segunda imagem anexada, não dando para carregar nos links que estão em cima, à direita e em baixo por isso sou forçado a ter que adicionar o Record.pt à lista branca do Ublock Origin e por conseguinte levo com esta publicidade em cada separador e ainda com vídeos de publicidade antes dos vídeos propriamente ditos do mesmo site começarem.
    Em segunda-feira, 24 de agosto de 2020, 01:13:00 WEST, Serpa<notifications@github.com> escreveu:  
 
 


Duplicate of #12
