### ISSUE TITLE
Vídeos do Record.pt param todos os segundos

### ISSUE THREAD

**Issue by Windows10User2** [dippas/DeleteNonio#16]
Os vídeos do Record.pt param todos os segundos quando esta extensão está ativada. Parece que só se começa a ter este problema a partir do segundo vídeo que se visualiza.

**Comment by dippas** [comment]
@Windows10User2  não consigo replicar este issue nem no Chrome nem no Firefox

**Comment by dippas** [comment]
@Windows10User2  é problema do site mesmo, ao desligar a extensão acontece o mesmo:

![image](https://user-images.githubusercontent.com/10220287/99666041-55d33a00-2a62-11eb-911f-731556056288.png)

**Comment by dippas** [comment]
@Windows10User2  testei novamente e acontece so no chrome (mas nem sempre - com ou sem extensão ativa). no Firefox corre bem.

**Comment by Windows10User2** [comment]
Tenho este problema no Kiwi Browser no Android com o uBlock Origin desativado (visto que quando está ativado tenho problemas neste site).    Em quinta-feira, 19 de novembro de 2020, 12:36:50 WET, Serpa<notifications@github.com> escreveu:  
 
 


@Windows10User2 testei novamente e acontece so no chrome (mas nem sempre - com ou sem extensão ativa). no Firefox corre bem.

**Comment by dippas** [comment]
@Windows10User2  a extensão so suporta Firefox, Chrome e o novo EDGE(chromium)
