### ISSUE TITLE
Notícias do Tribuna Expresso vão parar à secção de iniciar sessão

### ISSUE THREAD

**Issue by Windows10User2** [dippas/DeleteNonio#17]
As notícias do Tribuna Expresso vão parar à secção de iniciar sessão após serem abertas ao invés da parte de cima da notícia (que tem o título).

**Comment by dippas** [comment]
@Windows10User2  não consigo replicar este issue. aqui fica um print de uma noticia apos o deletenonio funcionar:

![image](https://user-images.githubusercontent.com/10220287/99664965-e3158f00-2a60-11eb-9070-5c5003ac3afe.png)
