### ISSUE TITLE
Sites

### ISSUE THREAD

**Issue by hlourencoam** [dippas/DeleteNonio#19]
Boas,

há sites que ainda não foram adicionados e que têm Nonio que são eles:

https://menshealth.pt
https://www.womenshealth.pt
https://www.noticiasmagazine.pt
https://www.delas.pt
https://www.voltaaomundo.pt

**Comment by dippas** [comment]
@hlourencoam  obrigado pela lista, assim que puder irei tratar disto

**Comment by dippas** [comment]
@hlourencoam  adicionados na v1.6.5, é aguardar pelas atualizações das webstores
