### ISSUE TITLE
Uso de cpu alto

### ISSUE THREAD

**Issue by hsl1** [dippas/DeleteNonio#2]
funciona no site tvi24 tambem mas de modo geral subiu o uso do cpu para mais de 80%
o botão by me a cofee tem erro no link ;)

Chrome 81

**Comment by dippas** [comment]
@hsl1  olá!

> o botão by me a cofee tem erro no link ;)

podes explicar melhor? acabei de testar e o link funciona bem!

quanto ao uso de cpu subir para mais de 80% vou fazer testes e volto a entrar em contato

**Comment by hsl1** [comment]
clica no botão da extensão buy me a coffee e ves que falta um H no inicio.
Quanto ao cpu agora está a 20% se abrir um site desses que tenha o nonio sobe logo para 80

**Comment by dippas** [comment]
@hsl1  eu vejo isto (e clicando vai parar ao sitio certo)

![image](https://user-images.githubusercontent.com/10220287/79575323-81033e80-80b9-11ea-8a87-07e9773b849b.png)

**Comment by hsl1** [comment]
Clica no botão da própria extensão

**Comment by dippas** [comment]
> 
> 
> Clica no botão da própria extensão ao pé da barra de endereço

Desculpa não percebo, que própria extensão? podes mandar um print sff?

**Comment by hsl1** [comment]
https://prnt.sc/s18gcf

**Comment by dippas** [comment]
Ah ok claro. que estupidez :) esqueço-me disso! vou corrigir. Obrigado. Se ias me comprar cafe agradeço :)

**Comment by hsl1** [comment]
Veja tambem a questão da cpu https://prnt.sc/s18dxk pq sobe tanto ?

**Comment by dippas** [comment]
@hsl1  fiz vários testes e não consegui relacionar nunca a extensão com a subida de percentagem de CPU.

Deixo aqui 2 exemplos de testes que fiz:

1.  site que não está abrangido pela extensão e com a extensão ligada no chrome
![image](https://user-images.githubusercontent.com/10220287/79580953-ab58fa00-80c1-11ea-865c-06b1fa0a12c0.png)

2.  site que está abrangido pela extensão - tvi24 - e após o codigo ter sido executado

![image](https://user-images.githubusercontent.com/10220287/79580915-9bd9b100-80c1-11ea-9bbc-53d156c20b18.png)

A subida  de CPU no chrome em média entre estes 2 testes foi de 2 a 3%, o que é normal dado que o site da  tvi24 é mais pesado que o outro testado.

Do que vejo não é um problema causado pela extensão em si.

**Comment by dippas** [comment]
O link do "buy me a coffee" já está corrigido na nova versão 1.4.2 :)

**Comment by hsl1** [comment]
site tvi24 https://prnt.sc/s19kro nos sites sem nonio não sobe tanto

**Comment by dippas** [comment]
so para fazer um despite faça 2 testes:

1º entre no site da tvi24 (nesssa mesma pagina onde esta a obter esse valor alto) mas desactive a extensão e veja o valor

2º va a outro site onde a extensão funciona (ex: expresso.pt) e veja se o valor aumenta tambem.

Todos os meus testes apontam para que não, mas faça os seus despites desse lado.
