### ISSUE TITLE
Deixou de funcionar no kiwi browser

### ISSUE THREAD

**Issue by MrFJ11** [dippas/DeleteNonio#20]
Desde o verão que não consigo ver as notícias sem o chato do nonio

Uso o kiwi browser com a engine 94 no android 11 e costumo usar o violentmokey com o script.

Experimentei também com a extensão e o nonio chateia sempre, mesmo em ambos os casos no modo desktop.

De momento não consigo testar os blockers num desktop para despistar a possibilidade de ser meu browser.

Alguém com feedback?

Agradecido pelo teu trabalho!

**Comment by MrFJ11** [comment]
Well, 

•• Xiaomi F3 - Android 11 ••

   • Kiwi browser 94.0.4606.56 Google play

Extensão, userscript pelo tampermonkey beta e não beta, violentmonkey beta e não beta.. Nada.. Mudei do meu dns nextdns para os da Google, cloudfire, operadora, 4g.. nada.


   • Kiwi browser Dev 1394197403 de 29/10 - github

Igual à versão google play.


   •Firefox nightly 95.0a1 - Google play

Consegui meter o geasymonkey a trabalhar mas não carregou o script.
Já a sua extensão, parece estar a funcionar mas não altera nada nos sites JN, Record e mais uns quantos.


   •Fennec 93.1.0 - fdroid

Igual ao firefox


   • Firefox 68.4.1 - apkmirror

Carregou todos as extensões, scripts e afins e nada. Continuam os logins a ocultar a notícia.
Também tentei usar useragent para Windows 10, etc, e nada.



•• Redmi 8 - Android 10 ••

   • Kiwi browser 94.0.4606.56 Google play

Os mesmos sintomas que no xiaomi F3.



•• Samsung J8 - Android 10 ••

   • Kiwi browser 94.0.4606.56 Google play

Os mesmos sintomas que no xiaomi F3 e redmi8



•• Huawei g6-u10 - Android 4.4.2 ••

   • Kiwi browser git210216 (chrome 88.0.4324.152) - github

Ainda consigo ler a notícia, só por o telemóvel ser muito mais lento a renderizar, mas acaba por aparecer os logins tanto na sua extensão como no script nos Xmonkey.



Desculpa a massada mas enfim. Só me vem a cabeça que eles colocaram outra implementação no código da página, por há uns meses funfava sem stress.
Mas como dá tudo bem no seu setup, logo à primeira, não percebo então o que possa ser, visto que usei 4 dispositivos diferentes com várias versões de browser/sistemas android.

Melhor feedback que isto não consigo dar, embora diferente ;)

Desisto, lol.

Abraço!

**Comment by dippas** [comment]
•Firefox nightly 95.0a1 - Google play - aqui da para usar sem ser por User Script , experimenta usar por extensão , seguir passos aqui https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/ e de feedback.

Mais que isto não consigo fazer também, pois como disse a extensão não é alterada desde 28 maio 2021, e testei o browser em questão no mesmo Sistema Operativo e funcionou sem problemas

**Comment by MrFJ11** [comment]
Sabe uma coisa? Estávamos a falar de coisas diferentes, e custou me a perceber isso, vou lhe explicar porquê:

O adblocker cosmético do kiwi browser já bloqueia o popup do nonio, MENOS, quando a notícia é para assinantes exclusivos em que o texto é escondido. Além disso também uso filtro de ads por dns, tipo pihole, só para agravar a situação.

Por isso é que me fazia confusão porque é que com o seu script ou extensão ligados ou desligados, as coisas ficavam iguais... Chegava àquelas notícias que toda a gente quer ler e aparecia o nonio, assinatura ou login... Na minha cabeça era tudo a mesma coisa, apenas com um nome diferente...
Daí cair no erro de achar que as coisas não estavam a funcionar bem.

Afinal desativando o adblock do kiwi, que vem ligado por defeito, aparece o popup impertinente ao fim de umas leituras.

Agora cheguei à conclusão que a sua extensão não serve para o propósito de mostrar o texto que está escondido nas notícias exclusivas... Que pelo JN está escarrapachado que a assinatura é pelo nonio... Daí de estar sempre a bater na mesma tecla.......


Tive esta trabalheira para nada. Só o estive a incomodar...


Já agora... Há maneira de mostrar as notícias esclusivas? Ou é impossível por não estar apenas escondidas no código fonte da página?

Abraço!

**Comment by dippas** [comment]
@MrFJ11  o que esta a falar são as paywalls , que não faz parte deste plugin - https://github.com/dippas/DeleteNonio/issues/15

Dado que realmente o plugin esta a funcionar corretamente no teu browser, agradecia que alterasses a tua classificação de 4 para 5 estrelas na webstore,  é uma forma de agradecimento.

Obrigado e um abraço.
