### ISSUE TITLE
Not working on Jornal de Negócios

### ISSUE THREAD

**Issue by liliana-djpg** [dippas/DeleteNonio#21]
I am using DeleteNonio v1.6.5 extension and as per description it should work on jornaldenegocios.pt/ articles. But it is not working. 

I am trying to access this article https://www.jornaldenegocios.pt/empresas/energia/detalhe/fusao-com-a-edp-renovaveis-esta-sempre-em-cima-da-mesa-diz-miguel-stilwell and can't get through the paywall and nonio prompt

**Comment by dippas** [comment]
@liliana-djpg  just tested across Jornal de negocio website and it is working fine as is been working. Regarding paywall this extension do not support bypassing paywalls, only the nonio popup
