### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by hsl1** [dippas/DeleteNonio#22]
Vejo algumas extensoes a usar isto The extension can now erase a login wall with no blinking popup thanks to MutationObserver, and can also work on mobile.twitter.com
Não sei se no caso não seria mais rápido a desaparecer pois por vezes nota-se tipo que aparece a janela e depois desaparece
https://javascript.info/mutation-observer

**Comment by dippas** [comment]
Estou a trabalhar numa versão totalmente nova (já que vou ter de ser forçado a alterar a extensão para mantê-la na chrome store devido a alterações da Store), so que não sei quando irei ter pronto a nova versão

**Comment by dippas** [comment]
Com a nova versao (v2+) foi impllementada a [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)
