### ISSUE TITLE
Não funciona no site n-tv.pt

### ISSUE THREAD

**Issue by Bruness** [dippas/DeleteNonio#3]
Não está a funcionar no https://www.n-tv.pt/

**Comment by dippas** [comment]
@Bruness  está corrigido na versão [1.4.6](https://github.com/dippas/DeleteNonio/releases/tag/v1.4.6)
Esta nova versão já está disponível no [Firefox](https://addons.mozilla.org/pt-PT/firefox/addon/deletenonio/) e em breve vai ficar disponível no [chrome ](https://chrome.google.com/webstore/detail/deletenonio/pcoliafiikpoggkobpfhcbkmmjlkonfa), apenas leva mais algum tempo a ser atualizado no chrome.

Aconselho a ter o auto-update ligado nas extensões ;)
