### ISSUE TITLE
expresso.pt

### ISSUE THREAD

**Issue by rigas40** [dippas/DeleteNonio#33]
era suposto funcionar no expresso.pt?
estou a usar chrome
exemplo
https://expresso.pt/orcamento-do-estado/2024-10-09-ate-onde-pode-gastar-o-governo--guia-para-perceber-o-debate-orcamental-em-sete-perguntas-e-respostas-382408f8

**Comment by dippas** [comment]
sim está na lista... não consigo reproduzir o erro. pode mostrar o screenshot do que está a ver?

**Comment by rigas40** [comment]
![2024-10-10_11-51](https://github.com/user-attachments/assets/24c355f8-8fed-4e22-8897-4daae617e787)
nao era suposto aparecer o artigo sem paywall ?

**Comment by dippas** [comment]
duplicado #15
