### ISSUE TITLE
RR não funciona

### ISSUE THREAD

**Issue by hsl1** [dippas/DeleteNonio#4]
Boas,
No site da radio renascença não funciona . Obrigado
![image](https://user-images.githubusercontent.com/11902467/89228964-7a50f680-d5d8-11ea-8dbe-03f80e0f5040.png)

**Comment by dippas** [comment]
@hsl1 Corrigido na v1.4.8

**Comment by hsl1** [comment]
ambos?

**Comment by dippas** [comment]
@hsl1 quanto ao expresso a correçáo sairá na v1.4.9. É esperar pelas atualizacoes das Stores

**Comment by hsl1** [comment]
ok aqui no chrome ainda vai na v1.4.7 pensei que ficasse na proxima versão ambos

**Comment by dippas** [comment]
o Chrome tem um problema que é apos submeter para revisão nao se pode submeter uma versão nova até ter algum feedback da equipa do chrome. Eu só reparei no issue do expresso e ja tinha submetido a v1.4.8 para revisãao, dai precisar de fazer uma nova versão.
