### ISSUE TITLE
Interferência com o modo escuro do Twitter

### ISSUE THREAD

**Issue by FlyingSligGuard** [dippas/DeleteNonio#6]
Testado na última versão do Firefox.
Com a extensão ativada:
![imagem](https://user-images.githubusercontent.com/11323277/89340499-c0b95a80-d697-11ea-8ba4-2be736c28aad.png)

Com a extensão desativada:
![imagem](https://user-images.githubusercontent.com/11323277/89340603-e5153700-d697-11ea-953d-4feb29fb838c.png)

**Comment by dippas** [comment]
@FlyingSligGuard  obrigado pelo aviso. Já está corrigido e disponivel. É esperar pelo update nas webstores (especialmente a do chrome demora um pouco)
