### ISSUE TITLE
Páginas ficam com duplo "elevador" e texto aumentado como se tivesse sido feito zoom

### ISSUE THREAD

**Issue by Windows10User2** [dippas/DeleteNonio#8]
Depois de instalar esta extensão na versão mais recente do Google Chrome, as páginas ficam com um duplo "elevador" e um site (pelo menos) fica com o texto aumentado como se tivesse sido feito zoom.

![Captura de Ecrã (20)](https://user-images.githubusercontent.com/57052438/89470585-0e0afa00-d774-11ea-9894-422fbb043b01.png)
![Captura de Ecrã (19)](https://user-images.githubusercontent.com/57052438/89470577-09464600-d774-11ea-9af2-c49a3bb598f3.png)

**Comment by dippas** [comment]
Duplicate of #6
