### ISSUE TITLE
Página desfigurada

### ISSUE THREAD

**Issue by Windows10User2** [dippas/DeleteNonio#9]
Na versão 
mais recente do Google Chrme x64 e após instalar e ativar a extensão DeleteNonio, a página ![Captura de Ecrã (21)](https://user-images.githubusercontent.com/57052438/89471039-0c8e0180-d775-11ea-96c9-f6d187e85d0f.png) fica desfigurada.

**Comment by dippas** [comment]
@Windows10User2  já está tudo corrigido só a espera que o Chrome aprove a nova versão na webstore. Neste momento é só esperar. Amanhã já deve estar disponível a nova versão.

**Comment by dippas** [comment]
Duplicate of #6

**Comment by Windows10User2** [comment]
> @Windows10User2 já está tudo corrigido só a espera que o Chrome aprove a nova versão na webstore. Neste momento é só esperar. Amanhã já deve estar disponível a nova versão.

Muito obrigado!

**Comment by Windows10User2** [comment]
> @Windows10User2 já está tudo corrigido só a espera que o Chrome aprove a nova versão na webstore. Neste momento é só esperar. Amanhã já deve estar disponível a nova versão.

Esqueci-me que também tenho este problema no novo Edge e parece que a versão é ainda mais antiga que a do Chrome. Como faço neste caso?

**Comment by dippas** [comment]
> > @Windows10User2 já está tudo corrigido só a espera que o Chrome aprove a nova versão na webstore. Neste momento é só esperar. Amanhã já deve estar disponível a nova versão.
> 
> Esqueci-me que também tenho este problema no novo Edge e parece que a versão é ainda mais antiga que a do Chrome. Como faço neste caso?

É a mesma resposta sobre a versão Chrome. Estão ambas neste momento por serem aprovados.

**Comment by Windows10User2** [comment]
Mas chegara amanhã como no caso da versão para o Chrome ou demorará mais tempo?
    Em quinta-feira, 6 de agosto de 2020, 01:05:57 WEST, Serpa<notifications@github.com> escreveu:  
 
 




@Windows10User2 já está tudo corrigido só a espera que o Chrome aprove a nova versão na webstore. Neste momento é só esperar. Amanhã já deve estar disponível a nova versão.


Esqueci-me que também tenho este problema no novo Edge e parece que a versão é ainda mais antiga que a do Chrome. Como faço neste caso?


É a mesma resposta sobre a versão Chrome. Estão ambas neste momento por serem aprovados.

**Comment by dippas** [comment]
@Windows10User2 ja estão ambas atualizadas.
